import csv
from collections import defaultdict


def calculate_average_speed(input_filepath, output_filepath):
    """
    Reads the tracking data with per-frame speeds and calculates the
    average speed for each unique object ID.
    """
    try:
        with open(input_filepath, 'r', newline='') as infile:
            reader = csv.reader(infile)
            header = next(reader)  # Skip header
            data_rows = list(reader)

        if not data_rows:
            print("The input file is empty. Cannot calculate averages.")
            return

        # { ID: [total_speed, count_of_frames_with_speed] }
        id_speed_totals = defaultdict(lambda: [0.0, 0])

        # Speed is in column 5 (index 5) of the tracking_with_speed.csv file
        SPEED_COLUMN_INDEX = 5

        for row in data_rows:
            try:
                track_id = int(row[1])
                # Speed is stored as a string, but sometimes as an empty string ("")
                speed_str = row[SPEED_COLUMN_INDEX]

                if speed_str:
                    speed = float(speed_str)

                    # Accumulate total speed and count frames where speed was calculated
                    id_speed_totals[track_id][0] += speed
                    id_speed_totals[track_id][1] += 1

            except ValueError:
                # Skip rows with non-numeric data, such as the original header
                continue
            except IndexError:
                # This should only happen if the input file format is wrong
                continue

        # 2. Calculate the average speed for each ID
        average_speeds = []
        # Sort the final output table by ID for clean reporting
        for track_id, (total_speed, count) in sorted(id_speed_totals.items()):
            if count > 0:
                avg_speed = total_speed / count
                average_speeds.append({
                    "ID": track_id,
                    "Total_Frames_Tracked": count,
                    "Average_Pixel_Speed_PS": f"{avg_speed:.2f}"
                })

        # 3. Write the final summary table
        fieldnames = ["ID", "Total_Frames_Tracked", "Average_Pixel_Speed_PS"]

        with open(output_filepath, 'w', newline='') as outfile:
            writer = csv.DictWriter(outfile, fieldnames=fieldnames)
            writer.writeheader()
            writer.writerows(average_speeds)

        print(f"\n✅ Analysis complete! Average speeds saved to {output_filepath}")

    except FileNotFoundError:
        print(f"\n❌ Error: Input file not found. Ensure 'tracking_with_speed.csv' exists.")
    except Exception as e:
        print(f"\n❌ An unexpected error occurred: {e}")


if __name__ == "__main__":
    # Input is the file generated by speed_calculator.py
    input_csv_file = '/Users/christosperontsis/Desktop/Python YOLO/Scripts/tracking_with_speed.csv'

    # Output file will be the final summary table
    output_csv_file = '/Users/christosperontsis/Desktop/Python YOLO/Scripts/car_average_speed_summary.csv'

    calculate_average_speed(input_csv_file, output_csv_file)